### ISSUE TITLE
feature_request(linting): Local appveyor.yml lint

### ISSUE THREAD

**Issue by Kristinita** [joaope/LocalAppVeyor#11]
### 1. Summary

It would be nice, if would be possible lint `appveyor.yml` file locally.

### 2. Argumentation

I can't find any CLI tools for linting `appveyor.yml`. Users needs use [**online validator**](https://ci.appveyor.com/tools/validate-yaml). It is not very convenient.

### 3. Examples on other apps

[**Travis Client**](https://github.com/travis-ci/travis.rb) [**has this feature**](https://stackoverflow.com/a/35607499/5951529) for `.travis.yml` files:

    travis lint <path to your .travis.yml>

Thanks.

**Comment by joaope** [comment]
That's a really cool idea. For that to happen I imagine the current deserializer would have to read (and validate) ALL sections whilst currently it only cares about the subset the engine supports. Let me have a thought about it. Ideas and code are welcome tho :)

**Comment by joaope** [comment]
Latest [release](https://github.com/joaope/LocalAppVeyor/releases) adds the ability to lint `appveyor.yml` through [`lint` command](https://github.com/joaope/LocalAppVeyor#-lint-command). It makes use of AppVeyor's REST API so it obviously needs an internet connection but correctness is guaranteed against whatever AppVeyor itself considers valid, which I think is a good compromise.

Note: localappveyor is now a global .NET core tool with a more straight-forward [installation process](https://github.com/joaope/LocalAppVeyor#install).
