### ISSUE TITLE
Error while parsing appveyor.yml

### ISSUE THREAD

**Issue by denizzzka** [joaope/LocalAppVeyor#115]
```
Z:\druntime>LocalAppVeyor lint --token=v2.dr7k***85kx
Validating 'Z:\druntime\appveyor.yml'...
Connecting to AppVeyor validation API...
YAML configuration file is valid.

Z:\druntime>LocalAppVeyor build
Error while parsing 'Z:\druntime\appveyor.yml' file. Build aborted.
```
(I don't know how to enable more verbose output)

This appveyor.yml file is here: https://github.com/dlang/druntime/blob/master/appveyor.yml
This is well-known project, most likely file is valid. It is not contains not supported build steps.

**Comment by joaope** [comment]
> This appveyor.yml file is here: https://github.com/dlang/druntime/blob/master/appveyor.yml

The very last line `test_script: true` shouldn't really be valid from AppVeyor perspective. All [documentation points to `test_script` being a script block](https://www.appveyor.com/docs/appveyor-yml/). Not sure what `test_script: true` means. If you can point me to some kind of documentation to where that's a valid scenario please do let me know.

That being said I assume AppVeyor just ignores it so I've updated the tool to do the same.

You can get latest.

```
dotnet tool update -g localappveyor
```

Thanks for reporting this.

**Comment by denizzzka** [comment]
Fixed, thanks!
