### ISSUE TITLE
Produce binaries\packages for different runtimes

### ISSUE THREAD

**Issue by joaope** [joaope/LocalAppVeyor#7]
Find the best strategy to easily produce and deploy binaries for a chosen set of [RIDs](https://github.com/dotnet/corefx/blob/master/pkg/Microsoft.NETCore.Platforms/runtime.json).

More info: [.NET Core Application Deployment](https://docs.microsoft.com/en-us/dotnet/articles/core/deploying/index)

**Comment by w0rp** [comment]
Because the project is so tied to AppVeyor, and AppVeyor lets you build binaries, you could consider building some binaries in AppVeyor, so you could continuously deliver this tool.

**Comment by joaope** [comment]
This is now packed and published as a .NET Core CLI global tool.
